#!/bin/bash

cd ~/Project/Checkstep/web

pwd

ls -al | grep env
source ${PWD}/.env

if [[ -z "${VITE_OPEN_API_PASSWORD}" ]]; then
  echo "Not found"
else
  echo ${VITE_OPEN_API_PASSWORD}
  curl https://api.staging.checkstep.com/openapi.json -u dev:${VITE_OPEN_API_PASSWORD} -o data/openapi.json --create-dirs --fail

  npm run types

  npm run prettier
fi
