require('options')
require('keymaps')
require('workflows')
require('plugins.lazy')
require('plugins.tele')
require('plugins.treesitter')
require('plugins.lsp')
require('plugins.lualine')
require('plugins.ctrlp')
require('plugins.obsidian')
require('plugins.keymaps')
require('plugins.options')

